source ../environment.sh
#source jobid.sh
export jobid=LFV_808v1
export MEGAPATH=/hdfs/store/user/fmeng/
export blind='YES'
export systematic=none
export isZTauTau=false
export isInclusive=false
export isRealData=true
