# Get common recipes
recipes = ENV['fsa'] + '/PlotTools/rake/recipes.rake'
import recipes

$jobid = ENV['jobid']

# Figure out what run period we are in
$period = '8TeV'
PU = ENV['PU']
#if $jobid.include? '8TeV'
#  $period = '8TeV'
#end


################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end
#
samples = Hash[
  "Singlet" => get_sample_names('ST_t'),
  "HiggsGGLFV" => get_sample_names('GluGlu_LFV_HToMuTau'),
  "HiggsGG" => get_sample_names('GluGlu'),
  "HiggsVBF" => get_sample_names('VBF'),
  "HiggsVBFLFV" => get_sample_names('VBF_LFV_HToMuTau'),
  #"TTBar" =>  get_sample_names('TT_TuneCUETP8M1_13TeV-powheg-pythia8'),
  "TTBar" =>  get_sample_names('TT_TuneCUETP8M1_13TeV-powheg-pythia8-evtgen'),
  "WJets" =>  get_sample_names('WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8'),
  "WZeroJets" =>  get_sample_names('WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "WOneJets" =>  get_sample_names('W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "WTwoJets" =>  get_sample_names('W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "WThreeJets" =>  get_sample_names('W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "WFourJets" =>  get_sample_names('W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "DYZeroJets" =>  get_sample_names('DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "DYOneJets" =>  get_sample_names('DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "DYTwoJets" =>  get_sample_names('DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "DYThreeJets" =>  get_sample_names('DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "DYFourJets" =>  get_sample_names('DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "DYAmcJets" => Array['DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8'],
  "DYJets" => Array['DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'],
  "DYJetsRedo2To4" => Array['DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'],
  "ZTauTauZeroJets" =>  get_sample_names('ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "ZTauTauOneJets" =>  get_sample_names('ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "ZTauTauTwoJets" =>  get_sample_names('ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "ZTauTauThreeJets" =>  get_sample_names('ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "ZTauTauFourJets" =>  get_sample_names('ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "ZTauTauJets" => Array['ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'],
  "ZTauTauJetsRedo2To4" => Array['ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8','ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'],
  #"ZTauTauZeroJets" => get_sample_names('ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8'),
  "ZTauTauAmcJets" => Array['ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8'],
  "SMHiggs" =>  Array['GluGluToHToTauTau_M-125_13TeV-powheg-pythia6','VBF_HToTauTau_M-125_13TeV-powheg-pythia6'],
  "SingleTop" => get_sample_names('ST'),
  #"DiBoson" => Array['WWTo2L2Nu_13TeV-powheg','WZ_TuneCUETP8M1_13TeV-pythia8','ZZ_TuneCUETP8M1_13TeV-pythia8']
  "DiBoson" => Array['WW_TuneCUETP8M1_13TeV-pythia8','WZ_TuneCUETP8M1_13TeV-pythia8','ZZ_TuneCUETP8M1_13TeV-pythia8'],
#  "DiBoson" => Array['WZ_TuneCUETP8M1_13TeV-pythia8','ZZ_TuneCUETP8M1_13TeV-pythia8'],
  "Data2015C" => get_sample_names('data_SingleMuon_Run2015C'),
  "Data2015D" => get_sample_names('data_SingleMuon_Run2015D'),
  "Data2016B" => get_sample_names('data_SingleMuon_Run2016B'),
  "Data2016C" => get_sample_names('data_SingleMuon_Run2016C'),
  "Data2016D" => get_sample_names('data_SingleMuon_Run2016D')
]

# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end

################################################################################
## Recipes to analyze the GG channel of the LFV HToMuTau analysis
##  targets:
##     mt
################################################################################

##use $PU = false for samples with no pileup
task :analyzeSpring2016WjetsandDatafakerate => get_analyzer_results("AnalyzeLFVMuMuTau.py",samples['Data2016B']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['Data2016C']+samples['Data2016D'])
task :analyzeSpring2016WjetsandDatafakeratemakeup => get_analyzer_results("AnalyzeLFVMuMuTau.py",samples['DYFourJets'])




task :analyzeSpring2016WjetsandDataDM => get_analyzer_results("AnalyzeLFVMuTauTdecaymold.py",samples['WZeroJets']+samples['Data2016B']+samples['WOneJets']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['TTBar']+samples['HiggsVBF']+samples['HiggsGG']+samples['ZTauTauZeroJets']+samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets']+samples['ZTauTauFourJets']+samples['DiBoson']+samples['SingleTop'])


#task :analyzeSpring2016WjetsandData => get_analyzer_results("AnalyzeLFVMuTau.py",samples['SingleTop']+samples['WZeroJets']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['Data2016B']+samples['WOneJets']+samples['Data2016C']+samples['Data2016D']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['TTBar']+samples['HiggsVBF']+samples['ZTauTauZeroJets']+samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets']+samples['ZTauTauFourJets']+samples['DiBoson']+samples['HiggsGG'])
task :analyzeSpring2016WjetsandData => get_analyzer_results("AnalyzeLFVMuTau.py",samples['ZTauTauZeroJets']+samples['WZeroJets']+samples['SingleTop']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['Data2016B']+samples['WOneJets']+samples['Data2016C']+samples['Data2016D']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['TTBar']+samples['HiggsVBF']+samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets']+samples['ZTauTauFourJets']+samples['DiBoson']+samples['HiggsGG'])

task :analyzeSpring2016Wjetfake => get_analyzer_results("AnalyzeLFVMuTauwjets_tune.py",samples['ZTauTauZeroJets']+samples['WZeroJets']+samples['SingleTop']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['Data2016B']+samples['WOneJets']+samples['Data2016C']+samples['Data2016D']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['TTBar']+samples['HiggsVBF']+samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets']+samples['ZTauTauFourJets']+samples['DiBoson']+samples['HiggsGG'])




task :analyzeSpring2016WjetsandDatajesdown => get_analyzer_results("AnalyzeLFVMuTaujesdown.py",samples['WZeroJets']+samples['WOneJets']+samples['Data2016B']+samples['Data2016C']+samples['Data2016D']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['TTBar']+samples['HiggsVBF']+samples['HiggsGG']+samples['ZTauTauZeroJets']+samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets']+samples['ZTauTauFourJets']+samples['DiBoson']+samples['SingleTop'])


task :analyzeSpring2016WjetsandDatajesup => get_analyzer_results("AnalyzeLFVMuTaujesup.py",samples['WZeroJets']+samples['WOneJets']+samples['Data2016B']+samples['Data2016C']+samples['Data2016D']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['TTBar']+samples['HiggsVBF']+samples['HiggsGG']+samples['ZTauTauZeroJets']+samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets']+samples['ZTauTauFourJets']+samples['DiBoson']+samples['SingleTop'])



task :analyzeSpring2016WjetsandDatauesdown => get_analyzer_results("AnalyzeLFVMuTauuesdown.py",samples['WZeroJets']+samples['WOneJets']+samples['Data2016B']+samples['Data2016C']+samples['Data2016D']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['TTBar']+samples['HiggsVBF']+samples['HiggsGG']+samples['ZTauTauZeroJets']+samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets']+samples['ZTauTauFourJets']+samples['DiBoson']+samples['SingleTop'])

task :analyzeSpring2016WjetsandDatauesup => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['WZeroJets']+samples['WOneJets']+samples['Data2016B']+samples['Data2016C']+samples['Data2016D']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['TTBar']+samples['HiggsVBF']+samples['HiggsGG']+samples['ZTauTauZeroJets']+samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets']+samples['ZTauTauFourJets']+samples['DiBoson']+samples['SingleTop'])



task :analyzeSpring2016WjetsandDatatesdown => get_analyzer_results("AnalyzeLFVMuTautesdown.py",samples['WZeroJets']+samples['WOneJets']+samples['Data2016B']+samples['Data2016C']+samples['Data2016D']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['TTBar']+samples['HiggsVBF']+samples['HiggsGG']+samples['ZTauTauZeroJets']+samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets']+samples['ZTauTauFourJets']+samples['DiBoson']+samples['SingleTop'])

task :analyzeSpring2016WjetsandDatatesup => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['WZeroJets']+samples['WOneJets']+samples['Data2016B']+samples['Data2016C']+samples['Data2016D']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['DYZeroJets']+samples['DYOneJets']+samples['DYTwoJets']+samples['DYThreeJets']+samples['DYFourJets']+samples['TTBar']+samples['HiggsVBF']+samples['HiggsGG']+samples['ZTauTauZeroJets']+samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets']+samples['ZTauTauFourJets']+samples['DiBoson']+samples['SingleTop'])


task :analyzeSpring2016WjetsandDatatrial => get_analyzer_results("AnalyzeLFVMuTaubeforenewTuning.py",samples['HiggsVBF']+samples['HiggsGG'])
task :analyzeSpring2016WjetsandDataBDT => get_analyzer_results("AnalyzeLFVMuTauBDTnew.py",samples['HiggsGGLFV']+samples['HiggsVBFLFV']+samples['WTwoJets']+samples['WThreeJets']+samples['WFourJets']+samples['WZeroJets'])













task :analyzeSpring2016WjetsandData_makeup => get_analyzer_results("AnalyzeLFVMuTau.py",samples['Data2016D'])

task :analyzeSpring2016WjetsandDatafakesdown_makeup => get_analyzer_results("AnalyzeLFVMuTaufakesdown.py",samples['DYOneJets'])

task :analyzeSpring2016WjetsandDatafakesup_makeup => get_analyzer_results("AnalyzeLFVMuTaufakesup.py",samples['ZTauTauOneJets'])

task :analyzeSpring2016WjetsandDatajesdown_makeup => get_analyzer_results("AnalyzeLFVMuTaujesdown.py",samples['ZTauTauOneJets']+samples['ZTauTauTwoJets']+samples['ZTauTauThreeJets'])

task :analyzeSpring2016WjetsandDatajesup_makeup => get_analyzer_results("AnalyzeLFVMuTaujesup.py",samples['DiBoson'])

task :analyzeSpring2016WjetsandDatatesdown_makeup => get_analyzer_results("AnalyzeLFVMuTautesdown.py",samples['ZTauTauOneJets'])

task :analyzeSpring2016WjetsandDatatesup_makeup => get_analyzer_results("AnalyzeLFVMuTautesup.py",samples['WTwoJets']+samples['Data2016C']+samples['Data2016D']+samples['DYZeroJets'])

task :analyzeSpring2016WjetsandDatauesdown_makeup => get_analyzer_results("AnalyzeLFVMuTauuesdown.py",samples['WThreeJets']+samples['Data2016C'])

task :analyzeSpring2016WjetsandDatauesup_makeup => get_analyzer_results("AnalyzeLFVMuTauuesup.py",samples['DYOneJets'])
