mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/ZZTo4L_13TeV-amcatnloFXFX-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_ZZTo4L_13TeV-amcatnloFXFX-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016E.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016F.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016E.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016E.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016E.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_data_SingleMuon_Run2016E.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016B.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016F.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016F.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016F.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_data_SingleMuon_Run2016F.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016C.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016B.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016B.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016B.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_data_SingleMuon_Run2016B.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016D.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016C.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016C.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016C.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_data_SingleMuon_Run2016C.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016D.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016D.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016D.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_data_SingleMuon_Run2016D.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WW_TuneCUETP8M1_13TeV-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZ_TuneCUETP8M1_13TeV-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WW_TuneCUETP8M1_13TeV-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WW_TuneCUETP8M1_13TeV-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WW_TuneCUETP8M1_13TeV-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_WW_TuneCUETP8M1_13TeV-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/ZZ_TuneCUETP8M1_13TeV-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZ_TuneCUETP8M1_13TeV-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WZ_TuneCUETP8M1_13TeV-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/WZ_TuneCUETP8M1_13TeV-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_WZ_TuneCUETP8M1_13TeV-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016G.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/ZZ_TuneCUETP8M1_13TeV-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/ZZ_TuneCUETP8M1_13TeV-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/ZZ_TuneCUETP8M1_13TeV-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_ZZ_TuneCUETP8M1_13TeV-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016H.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016G.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016G.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016G.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_data_SingleMuon_Run2016G.log &
sleep 10s
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016H.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuTau.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016H.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuTau/data_SingleMuon_Run2016H.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuTau_data_SingleMuon_Run2016H.log &
sleep 10s
