mkdir -p `dirname results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_v14/ZHToTauTau_M125_13TeV_powheg_pythia8.root`
mkdir -p `dirname results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_v14/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_v14/ZHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTauPostBDT_progress_v14.py inputs/LFV_Mar15_mc/ZHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_v14/ZHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Mar15_mc_AnalyzeLFVMuTauPostBDT_progress_v14_ZHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_v14/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_v14/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTauPostBDT_progress_v14.py inputs/LFV_Mar15_mc/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_v14/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_Mar15_mc_AnalyzeLFVMuTauPostBDT_progress_v14_ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
#using farmout:1
#dry run:1
export megatarget=results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_v14/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTauPostBDT_progress_v14.py inputs/LFV_Mar15_mc/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.txt results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_v14/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Mar15_mc_AnalyzeLFVMuTauPostBDT_progress_v14_VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
