mkdir -p `dirname results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_vMergy01/data_SingleMuon_Run2016G.root`
mkdir -p `dirname results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_vMergy01/data_SingleMuon_Run2016H.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_vMergy01/data_SingleMuon_Run2016G.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTauPostBDT_progress_vMergy01.py inputs/LFV_Mar15_mc/data_SingleMuon_Run2016G.txt results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_vMergy01/data_SingleMuon_Run2016G.root --verbose >& batch_logs/results_LFV_Mar15_mc_AnalyzeLFVMuTauPostBDT_progress_vMergy01_data_SingleMuon_Run2016G.log &
sleep 10s
mkdir -p `dirname results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_vMergy01/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_vMergy01/data_SingleMuon_Run2016H.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTauPostBDT_progress_vMergy01.py inputs/LFV_Mar15_mc/data_SingleMuon_Run2016H.txt results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_vMergy01/data_SingleMuon_Run2016H.root --verbose >& batch_logs/results_LFV_Mar15_mc_AnalyzeLFVMuTauPostBDT_progress_vMergy01_data_SingleMuon_Run2016H.log &
sleep 10s
#using farmout:1
#dry run:1
export megatarget=results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_vMergy01/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTauPostBDT_progress_vMergy01.py inputs/LFV_Mar15_mc/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Mar15_mc/AnalyzeLFVMuTauPostBDT_progress_vMergy01/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Mar15_mc_AnalyzeLFVMuTauPostBDT_progress_vMergy01_ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
