mkdir -p `dirname results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M900_13TeV_powheg_pythia8.root`
mkdir -p `dirname results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M300_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M900_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune.py inputs/LFV_HighMass/GluGlu_LFV_HToMuTau_M900_13TeV_powheg_pythia8.txt results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M900_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_HighMass_AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune_GluGlu_LFV_HToMuTau_M900_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M450_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M300_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune.py inputs/LFV_HighMass/GluGlu_LFV_HToMuTau_M300_13TeV_powheg_pythia8.txt results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M300_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_HighMass_AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune_GluGlu_LFV_HToMuTau_M300_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M600_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M450_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune.py inputs/LFV_HighMass/GluGlu_LFV_HToMuTau_M450_13TeV_powheg_pythia8.txt results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M450_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_HighMass_AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune_GluGlu_LFV_HToMuTau_M450_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M750_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M600_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune.py inputs/LFV_HighMass/GluGlu_LFV_HToMuTau_M600_13TeV_powheg_pythia8.txt results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M600_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_HighMass_AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune_GluGlu_LFV_HToMuTau_M600_13TeV_powheg_pythia8.log &
sleep 10s
#using farmout:1
#dry run:1
export megatarget=results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M750_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune.py inputs/LFV_HighMass/GluGlu_LFV_HToMuTau_M750_13TeV_powheg_pythia8.txt results/LFV_HighMass/AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune/GluGlu_LFV_HToMuTau_M750_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_HighMass_AnalyzeLFVMuTau_HighMassTriggerEffi_200Tune_GluGlu_LFV_HToMuTau_M750_13TeV_powheg_pythia8.log &
sleep 10s
