mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/GluGluHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_GluGluHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WGstarToLNuEE_13TeV-madgraph.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WGstarToLNuMuMu_13TeV-madgraph.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WGstarToLNuEE_13TeV-madgraph.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WGstarToLNuEE_13TeV-madgraph.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WGstarToLNuEE_13TeV-madgraph.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WGstarToLNuEE_13TeV-madgraph.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/VBFHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WGstarToLNuMuMu_13TeV-madgraph.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WGstarToLNuMuMu_13TeV-madgraph.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WGstarToLNuMuMu_13TeV-madgraph.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WGstarToLNuMuMu_13TeV-madgraph.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/VBFHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/VBFHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/VBFHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_VBFHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016H.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WminusHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016H.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/data_SingleMuon_Run2016H.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016H.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_data_SingleMuon_Run2016H.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WplusHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WminusHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WminusHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WminusHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WminusHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WplusHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WplusHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WplusHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WplusHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ZHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ZHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016G.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016F.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016G.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/data_SingleMuon_Run2016G.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016G.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_data_SingleMuon_Run2016G.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016F.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/data_SingleMuon_Run2016F.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016F.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_data_SingleMuon_Run2016F.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016E.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016E.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/data_SingleMuon_Run2016E.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016E.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_data_SingleMuon_Run2016E.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016B.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016C.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016B.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/data_SingleMuon_Run2016B.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016B.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_data_SingleMuon_Run2016B.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016D.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016C.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/data_SingleMuon_Run2016C.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016C.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_data_SingleMuon_Run2016C.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016D.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/data_SingleMuon_Run2016D.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/data_SingleMuon_Run2016D.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_data_SingleMuon_Run2016D.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuEtrial.py inputs/LFV_reminiaod_feb21_data/ZZTo4L_13TeV-amcatnloFXFX-pythia8.txt results/LFV_reminiaod_feb21_data/AnalyzeLFVMuMuEtrial/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb21_data_AnalyzeLFVMuMuEtrial_ZZTo4L_13TeV-amcatnloFXFX-pythia8.log &
sleep 10s
