mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016D.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016H.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016D.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/data_SingleMuon_Run2016D.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016D.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_data_SingleMuon_Run2016D.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016H.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/data_SingleMuon_Run2016H.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016H.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_data_SingleMuon_Run2016H.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/GluGluHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_GluGluHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M200_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M300_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M200_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/GluGlu_LFV_HToMuTau_M200_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M200_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_GluGlu_LFV_HToMuTau_M200_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M450_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M300_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/GluGlu_LFV_HToMuTau_M300_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M300_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_GluGlu_LFV_HToMuTau_M300_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M600_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M450_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/GluGlu_LFV_HToMuTau_M450_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M450_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_GluGlu_LFV_HToMuTau_M450_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M750_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M600_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/GluGlu_LFV_HToMuTau_M600_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M600_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_GluGlu_LFV_HToMuTau_M600_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M900_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M750_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/GluGlu_LFV_HToMuTau_M750_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M750_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_GluGlu_LFV_HToMuTau_M750_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016F.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M900_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/GluGlu_LFV_HToMuTau_M900_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/GluGlu_LFV_HToMuTau_M900_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_GluGlu_LFV_HToMuTau_M900_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WGstarToLNuMuMu_13TeV-madgraph.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016F.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/data_SingleMuon_Run2016F.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016F.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_data_SingleMuon_Run2016F.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WGstarToLNuMuMu_13TeV-madgraph.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WGstarToLNuMuMu_13TeV-madgraph.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WGstarToLNuMuMu_13TeV-madgraph.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WGstarToLNuMuMu_13TeV-madgraph.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WGstarToLNuEE_13TeV-madgraph.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WGToLNuG_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WminusHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WGstarToLNuEE_13TeV-madgraph.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WGstarToLNuEE_13TeV-madgraph.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WGstarToLNuEE_13TeV-madgraph.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WGstarToLNuEE_13TeV-madgraph.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WplusHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WminusHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WminusHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WminusHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WminusHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WplusHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WplusHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WplusHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WplusHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ZHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ZHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016G.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ttHJetToTT_M125_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/VBFHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016G.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/data_SingleMuon_Run2016G.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016G.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_data_SingleMuon_Run2016G.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/VBFHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/VBFHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/VBFHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_VBFHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016E.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016E.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/data_SingleMuon_Run2016E.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016E.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_data_SingleMuon_Run2016E.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016B.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016C.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016B.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/data_SingleMuon_Run2016B.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016B.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_data_SingleMuon_Run2016B.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016C.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/data_SingleMuon_Run2016C.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/data_SingleMuon_Run2016C.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_data_SingleMuon_Run2016C.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
#using farmout:1
#dry run:1
export megatarget=results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_HighMassnewtest.py inputs/LFV_Feb5_2018_mc/ZZTo4L_13TeV-amcatnloFXFX-pythia8.txt results/LFV_Feb5_2018_mc/AnalyzeLFVMuTau_HighMassnewtest/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root --verbose >& batch_logs/results_LFV_Feb5_2018_mc_AnalyzeLFVMuTau_HighMassnewtest_ZZTo4L_13TeV-amcatnloFXFX-pythia8.log &
sleep 10s
