mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root`
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/GluGluHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_GluGluHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WminusHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WplusHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WminusHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/WminusHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WminusHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_WminusHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WplusHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/WplusHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WplusHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_WplusHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016G.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ZHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ZHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/VBFHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016G.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016G.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016G.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_data_SingleMuon_Run2016G.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/VBFHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/VBFHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/VBFHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_VBFHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016H.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016F.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016H.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016H.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016H.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_data_SingleMuon_Run2016H.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016F.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016F.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016F.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_data_SingleMuon_Run2016F.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016E.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016E.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016E.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016E.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_data_SingleMuon_Run2016E.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016B.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016B.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016B.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016B.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_data_SingleMuon_Run2016B.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016C.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016D.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016C.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016C.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016C.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_data_SingleMuon_Run2016C.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016D.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016D.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/data_SingleMuon_Run2016D.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_data_SingleMuon_Run2016D.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress_TES3_Fakshape.py inputs/LFV_reminiaod_feb18/ZZTo4L_13TeV-amcatnloFXFX-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress_TES3_Fakshape/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TES3_Fakshape_ZZTo4L_13TeV-amcatnloFXFX-pythia8.log &
sleep 10s
