mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/ZZTo4L_13TeV-amcatnloFXFX-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_ZZTo4L_13TeV-amcatnloFXFX-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016E.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016F.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016E.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016E.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016E.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_data_SingleMuon_Run2016E.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016B.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016F.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016F.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016F.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_data_SingleMuon_Run2016F.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016C.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016B.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016B.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016B.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_data_SingleMuon_Run2016B.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016D.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016C.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016C.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016C.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_data_SingleMuon_Run2016C.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016D.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016D.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016D.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_data_SingleMuon_Run2016D.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WW_TuneCUETP8M1_13TeV-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZ_TuneCUETP8M1_13TeV-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WW_TuneCUETP8M1_13TeV-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WW_TuneCUETP8M1_13TeV-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WW_TuneCUETP8M1_13TeV-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_WW_TuneCUETP8M1_13TeV-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/ZZ_TuneCUETP8M1_13TeV-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZ_TuneCUETP8M1_13TeV-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/WZ_TuneCUETP8M1_13TeV-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/WZ_TuneCUETP8M1_13TeV-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_WZ_TuneCUETP8M1_13TeV-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016G.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/ZZ_TuneCUETP8M1_13TeV-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/ZZ_TuneCUETP8M1_13TeV-pythia8.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/ZZ_TuneCUETP8M1_13TeV-pythia8.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_ZZ_TuneCUETP8M1_13TeV-pythia8.log &
sleep 10s
mkdir -p `dirname results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016H.root`
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016G.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016G.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016G.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_data_SingleMuon_Run2016G.log &
sleep 10s
#using farmout:1
#dry run:1
export megatarget=results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016H.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuMuMu.py inputs/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/data_SingleMuon_Run2016H.txt results/Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc/AnalyzeLFVMuMuMu/data_SingleMuon_Run2016H.root --verbose >& batch_logs/results_Trilepton_D_LFV_reminiaod_feb21_data_MC_LFV_reminiaod_feb21_mc_AnalyzeLFVMuMuMu_data_SingleMuon_Run2016H.log &
sleep 10s
