mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WminusHToTauTau_M125_13TeV_powheg_pythia8.root`
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WplusHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WminusHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/WminusHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WminusHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_WminusHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WplusHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/WplusHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WplusHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_WplusHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016G.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ZHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ZHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/VBFHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016G.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016G.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016G.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_data_SingleMuon_Run2016G.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/VBFHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/VBFHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/VBFHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_VBFHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016H.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016F.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016H.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016H.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016H.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_data_SingleMuon_Run2016H.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016F.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016F.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016F.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_data_SingleMuon_Run2016F.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ZTauTauJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_TT_TuneCUETP8M2T4_13TeV-powheg-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016E.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ZTauTauJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016E.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016E.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016E.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_data_SingleMuon_Run2016E.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016B.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016B.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016B.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016B.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_data_SingleMuon_Run2016B.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016C.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016D.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016C.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016C.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016C.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_data_SingleMuon_Run2016C.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016D.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/data_SingleMuon_Run2016D.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/data_SingleMuon_Run2016D.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_data_SingleMuon_Run2016D.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_DYJetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ZTauTau1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ZTauTau2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ZTauTau3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ZTauTau4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_VVTo2L2Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_WZJToLLLNu_TuneCUETP8M1_13TeV-amcnlo-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/ZZTo4L_13TeV-amcatnloFXFX-pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/ZZTo4L_13TeV-amcatnloFXFX-pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_ZZTo4L_13TeV-amcatnloFXFX-pythia8.log &
sleep 10s
mkdir -p `dirname results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root`
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/GluGluHToTauTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/GluGluHToTauTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_GluGluHToTauTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
#using farmout:1
#dry run:1
export megatarget=results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root
mkdir -p batch_logs
mega-farmout AnalyzeLFVMuTau_progress.py inputs/LFV_reminiaod_feb18/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.txt results/LFV_reminiaod_feb18/AnalyzeLFVMuTau_progress/GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.root --verbose >& batch_logs/results_LFV_reminiaod_feb18_AnalyzeLFVMuTau_progress_GluGlu_LFV_HToMuTau_M125_13TeV_powheg_pythia8.log &
sleep 10s
