cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDT/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDTjesup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDTjesdown/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDTtesup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDTtesdown/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDTuesup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDTuesdown/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDTbtagup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDTbtagdown/weights
