cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_MiniAODVtrial_sys/AnalyzeLFVMuTaujesup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_MiniAODVtrial_sys/AnalyzeLFVMuTaujesdown/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_MiniAODVtrial_sys/AnalyzeLFVMuTautesup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_MiniAODVtrial_sys/AnalyzeLFVMuTautesdown/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_MiniAODVtrial_sys/AnalyzeLFVMuTauuesup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_MiniAODVtrial_sys/AnalyzeLFVMuTauuesdown/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_MiniAODVtrial_sys/AnalyzeLFVMuTaubtagup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_MiniAODVtrial_sys/AnalyzeLFVMuTaubtagdown/weights
