cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDT_progress/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDT_progressjesup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDT_progressjesdown/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDT_progresstesup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDT_progresstesdown/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDT_progressuesup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDT_progressuesdown/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDT_progressbtagup/weights
cp -r ../lfvmutau/inputs/SMHTT_oct25/ LFV_BDT/AnalyzeLFVMuTauPostBDT_progressbtagdown/weights
