mv LFV_MiniAODVtrial_sys/AnalyzeLFVMuTauon LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau
mv LFV_MiniAODVtrial_sys/AnalyzeLFVMuTaujesupon LFV_MiniAODVtrial_sys/AnalyzeLFVMuTaujesup
mv LFV_MiniAODVtrial_sys/AnalyzeLFVMuTauuesupon LFV_MiniAODVtrial_sys/AnalyzeLFVMuTauuesup
mv LFV_MiniAODVtrial_sys/AnalyzeLFVMuTautesupon LFV_MiniAODVtrial_sys/AnalyzeLFVMuTautesup
mv LFV_MiniAODVtrial_sys/AnalyzeLFVMuTautesdownon LFV_MiniAODVtrial_sys/AnalyzeLFVMuTautesdown
mv LFV_MiniAODVtrial_sys/AnalyzeLFVMuTaujesdownon LFV_MiniAODVtrial_sys/AnalyzeLFVMuTaujesdown
mv LFV_MiniAODVtrial_sys/AnalyzeLFVMuTauuesdownon LFV_MiniAODVtrial_sys/AnalyzeLFVMuTauuesdown

