python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetAbsoluteFlavMap_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetAbsoluteFlavMap_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetAbsoluteFlavMap_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetAbsoluteFlavMap_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetAbsoluteFlavMap_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetAbsoluteFlavMap_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetAbsoluteFlavMap_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetAbsoluteFlavMap_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetAbsoluteMPFBias_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetAbsoluteMPFBias_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetAbsoluteMPFBias_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetAbsoluteMPFBias_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetAbsoluteMPFBias_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetAbsoluteMPFBias_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetAbsoluteMPFBias_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetAbsoluteMPFBias_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetAbsoluteScale_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetAbsoluteScale_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetAbsoluteScale_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetAbsoluteScale_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetAbsoluteScale_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetAbsoluteScale_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetAbsoluteScale_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetAbsoluteScale_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetAbsoluteStat_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetAbsoluteStat_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetAbsoluteStat_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetAbsoluteStat_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetAbsoluteStat_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetAbsoluteStat_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetAbsoluteStat_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetAbsoluteStat_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetFlavorQCD_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetFlavorQCD_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetFlavorQCD_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetFlavorQCD_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetFlavorQCD_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetFlavorQCD_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetFlavorQCD_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetFlavorQCD_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetFragmentation_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetFragmentation_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetFragmentation_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetFragmentation_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetFragmentation_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetFragmentation_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetFragmentation_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetFragmentation_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpDataMC_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpDataMC_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpDataMC_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpDataMC_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpDataMC_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpDataMC_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpDataMC_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpDataMC_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpPtBB_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpPtBB_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpPtBB_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpPtBB_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpPtBB_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpPtBB_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpPtBB_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpPtBB_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpPtEC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpPtEC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpPtEC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpPtEC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpPtEC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpPtEC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpPtEC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpPtEC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpPtEC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpPtEC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpPtEC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpPtEC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpPtEC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpPtEC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpPtEC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpPtEC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpPtHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpPtHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpPtHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpPtHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpPtHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpPtHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpPtHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpPtHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpPtRef_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpPtRef_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpPtRef_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpPtRef_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetPileUpPtRef_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetPileUpPtRef_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetPileUpPtRef_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetPileUpPtRef_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeBal_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeBal_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeBal_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeBal_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeBal_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeBal_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeBal_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeBal_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeFSR_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeFSR_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeFSR_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeFSR_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeFSR_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeFSR_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeFSR_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeFSR_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeJEREC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeJEREC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeJEREC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeJEREC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeJEREC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeJEREC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeJEREC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeJEREC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeJEREC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeJEREC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeJEREC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeJEREC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeJEREC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeJEREC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeJEREC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeJEREC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeJERHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeJERHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeJERHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeJERHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeJERHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeJERHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeJERHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeJERHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativePtBB_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativePtBB_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativePtBB_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativePtBB_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativePtBB_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativePtBB_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativePtBB_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativePtBB_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativePtEC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativePtEC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativePtEC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativePtEC1_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativePtEC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativePtEC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativePtEC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativePtEC1_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativePtEC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativePtEC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativePtEC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativePtEC2_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativePtEC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativePtEC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativePtEC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativePtEC2_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativePtHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativePtHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativePtHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativePtHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativePtHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativePtHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativePtHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativePtHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeStatEC_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeStatEC_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeStatEC_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeStatEC_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeStatEC_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeStatEC_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeStatEC_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeStatEC_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeStatFSR_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeStatFSR_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeStatFSR_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeStatFSR_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeStatFSR_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeStatFSR_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeStatFSR_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeStatFSR_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeStatHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeStatHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeStatHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeStatHF_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetRelativeStatHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetRelativeStatHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetRelativeStatHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetRelativeStatHF_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetSinglePionECAL_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetSinglePionECAL_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetSinglePionECAL_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetSinglePionECAL_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetSinglePionECAL_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetSinglePionECAL_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetSinglePionECAL_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetSinglePionECAL_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetSinglePionHCAL_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetSinglePionHCAL_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetSinglePionHCAL_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetSinglePionHCAL_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetSinglePionHCAL_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetSinglePionHCAL_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetSinglePionHCAL_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetSinglePionHCAL_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetTimePtEta_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetTimePtEta_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetTimePtEta_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetTimePtEta_13TeVDown    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 gg    0  Jes_JetTimePtEta_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 boost    0  Jes_JetTimePtEta_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_gg    0  Jes_JetTimePtEta_13TeVUp    tPt0   0
python plot_13TeV_vbfbined_QCD_36_v3.py LFV_MiniAODVtrial_sys/AnalyzeLFVMuTau/ collMass_type1 vbf_vbf    0  Jes_JetTimePtEta_13TeVUp    tPt0   0
